### ISSUE TITLE
Singletons without properties

### ISSUE THREAD

**Issue by mograff** [coldbox-modules/singleton-leak-detector#1]
Hello-
Love the project....I was getting an error because some of my singletons did not have properties. 

So to fix I added: 
**if ( !structkeyExists(md,'properties') )
    md.properties = [];**

to the $scopeSpy in the models/LeakAnalyzer.cfc line 117
```

/**
	* A mixin to add to our singleons we're tracking
	*/
	function $scopeSpy( required controller ) {
		var md = controller.getUtil().getInheritedMetaData( this );
		if ( !structkeyExists(md,'properties') )
			md.properties = [];
		var props = md.properties.map( function( prop ){ 
			return prop.name;
		} );

		// Return the variables scope...
		return variables
			// ... but ignore UDFs, CFCs (mostly for performance) and properties
			// Ignoring CONDITIONALS_SQL_MAP since it's part of the base ORM service
			.filter( function( k, v ) {
				return !isCustomFunction( v ) && !props.findNoCase( k ) && !isObject( v ) && k != 'CONDITIONALS_SQL_MAP';
			} );

	}
```

**Comment by bdw429s** [comment]
Good catch!  Can you send me a pull request for this change and I'll merge it.  You can just edit the file right here on Github if you want and when you save it will create a pull for you.

**Comment by elpete** [comment]
A nice one-line improvement to that is to use `param`:
```cfc
param md.properties = [];
```

**Comment by bdw429s** [comment]
FWIW I put in a ticket the other day for Lucee and Adobe to always contain an empty functions and properties array even when a CFC has no functions or properties.  I hate having to do these sort of checks!

**Comment by bdw429s** [comment]
https://github.com/coldbox-modules/singleton-leak-detector/pull/2
